version: '3.8'

services:
    piped:
        image: 1337kavin/piped:latest
        restart: unless-stopped
        ports:
            - "127.0.0.1:8080:8080"
        volumes:
            - ./config.properties:/app/config.properties
        environment:
            - PROXY_HOST=proxy
            - PROXY_PORT=1080
        depends_on:
            - postgres
            - proxy
            
    proxy:
        image: eclipse-temurin:21-jre
        restart: unless-stopped
        ports:
            - "127.0.0.1:1080:1080"
        environment:
            - DYNAMIC_PROXY_PORT=1080
        command: |
          bash -c "
            echo 'Proxy service placeholder' > /tmp/proxy.log &&
            while true; do
              echo 'Proxy service running...' >> /tmp/proxy.log &&
              sleep 60
            done
          "
            
    postgres:
        image: postgres:17-alpine
        restart: unless-stopped
        volumes:
            - ./data/db:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=piped
            - POSTGRES_USER=piped
            - POSTGRES_PASSWORD=changeme