version: '3.8'

services:
  piped-backend:
    build:
      context: .
      dockerfile: Dockerfile.proxy
    ports:
      - "8080:8080"
      - "1080:1080"
    environment:
      - PORT=8080
      - HTTP_WORKERS=4
      - ENABLE_DYNAMIC_PROXY=true
      - DYNAMIC_PROXY_PORT=1080
    volumes:
      - ./config.properties:/app/config.properties
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: piped
      POSTGRES_USER: piped
      POSTGRES_PASSWORD: changeme
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: