services:
    piped:
        image: 1337kavin/piped:latest
        restart: unless-stopped
        ports:
            - "8080:8080"
            - "1080:1080"
        volumes:
            - ./config.properties:/app/config.properties
        environment:
            - PORT=8080
            - DYNAMIC_PROXY_PORT=1080
        depends_on:
            - postgres
    postgres:
        image: postgres:17-alpine
        restart: unless-stopped
        volumes:
            - ./data/db:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=piped
            - POSTGRES_USER=piped
            - POSTGRES_PASSWORD=changeme